
import SubNavbar from "@/components/shared/SubNavbar";
import "./frontend.css";
import Navbar from "@/components/shared/Navbar";
import Sidebar from "@/components/shared/Sidebar";
import FrontNavbar from "@/components/shared/FrontNabvar";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased font-outfit -mt-24`}

        
      >


<FrontNavbar/>


{children}


    
      </body>
    </html>
  );
}
